### PR TITLE
aQGC cards for VVjj semileptonic VBS

### PR DESCRIPTION
**Pull request by asar0786**
These cards contains 9 samples required for VVjj semileptonic precess. They are

1. pp -> W+W- JJ  -> L+Nu QQ JJ
2. pp -> W+W- JJ ->  QQ L-Nu JJ
3. pp -> W+Z JJ ->  QQ L+L- JJ
4. pp -> W+Z JJ -> L+Nu QQ JJ
5 pp -> W+W+ JJ -> L+Nu QQ JJ
6. pp -> W-Z JJ -> L-Nu QQ JJ
7. pp -> W-Z JJ -> QQ L+L- JJ
8. pp -> W-W- JJ -> L-Nu QQ JJ
9. pp -> ZZ JJ -> L+L- QQ JJ

### CODE REVIEW

**Comment by efeyazgan** [comment]
Is there a reason that you do not make the PR to master? thanks.

**Comment by asar0786** [comment]
Hi, I was working on branch “mg265” because of the bug in previous version of Madgraph. So, I made the pull request to “mg265”.

**Comment by efeyazgan** [comment]
Is this supposed to be run only in 265? If not, I think you should use the master branch.

**Comment by asar0786** [comment]
This will not work on version older than mg265, currently master has older version..Thanks

**Comment by efeyazgan** [comment]
OK then.

**Comment by qliphy** [comment]
@asar0786   Can you remind me what is the bug in previous version?  Have you contacted the MG authors?

**Comment by govoni** [comment]
Dear All, may I ask whether it was checked that the two-lepton final state has enough statistics for a two-lepton analysis, and to check possible contaminations in the one-lepton case?

**Comment by ram1123** [comment]
> @asar0786 Can you remind me what is the bug in previous version? Have you contacted the MG authors?

@qliphy 
In the older version of madgraph we get error like below:

```
INFO: generate matrix element for decay only (1 - > N).
INFO: output standalone_msF /uscms_data/d3/asahmed/Gridpack2017/genproductions/bin/MadGraph5_aMCatNLO/aQGC_WPlepWPhadJJ_EWK_LO_NPle1_mjj100pt10/aQGC_WPlepWPhadJJ_EWK_LO_NPle1_mjj100pt10_gridpack/work/process/madspingrid/decay_me
INFO: Done 3.368
INFO: Compiling code
INFO: detect independant decays
INFO: Done in 7.56426692009s
INFO:
INFO: Estimating the maximum weight
INFO: *
INFO: Probing the first 75 events
INFO: with 400 phase space points
INFO:
INFO: No independent decay for one type of final states -> skip those events for the maximum weight computation
INFO:
INFO: Decaying the events...
INFO: Total number of events written: 0/1000
Command "launch" interrupted with error:
ZeroDivisionError : float division by zero
Please report this bug to developers
       More information is found in 'MS_debug'.

       Please attach this file to your report.
```

**Comment by qliphy** [comment]
@ram1123  Thanks! So you were using version 260 or 261?

**Comment by ram1123** [comment]
> @ram1123 Thanks! So you were using version 260 or 261?

We tried both. And saw same issue.

**Comment by qliphy** [comment]
Ok, thanks.  As mg265 is still being validated and not yet ready for official usages in CMS, would you please do a bit checks with your gridpacks? e.g. check the aQGC distributions... and if possible take into account of comment from @govoni

**Comment by ram1123** [comment]
> Dear All, may I ask whether it was checked that the two-lepton final state has enough statistics for a two-lepton analysis, and to check possible contaminations in the one-lepton case?

@govoni : These are aQGC sample. The requested statistics are enough as per our previous study. 

The contamination of 1 lepton case in 2 lepton case and vice-verse is tiny. So, our signal definiton of ZV and WV scenarios contains all 9 samples. If only one identified lepton found it goes to WV and if 2 then it goes to ZV case.

**Comment by ram1123** [comment]
> Ok, thanks. As mg265 is still being validated and not yet ready for official usages in CMS, would you please do a bit checks with your gridpacks? e.g. check the aQGC distributions... 

@qliphy : Yes, we will do this.

**Comment by agrohsje** [comment]
There was a bug in decay.py which I fixed ~3 weeks ago [1] . That should solve the problem you observed in 2.6.1. Would you mind testing? Then we could avoid using something that is still in validation. 
Cheers, Alexander.

[1] https://github.com/cms-sw/genproductions/blob/mg261/bin/MadGraph5_aMCatNLO/patches/0015-fix-critical-madspin-bug.patch

**Comment by govoni** [comment]
thanks +1

**Comment by asar0786** [comment]
> There was a bug in decay.py which I fixed ~3 weeks ago [1] . That should solve the problem you observed in 2.6.1. Would you mind testing? Then we could avoid using something that is still in validation.
> Cheers, Alexander.
> 
> [1] https://github.com/cms-sw/genproductions/blob/mg261/bin/MadGraph5_aMCatNLO/patches/0015-fix-critical-madspin-bug.patch

@agrohsje Okay, I will test with the recommendation, Hope I will finish it by tonight.

**Comment by agrohsje** [comment]
Did it work ?

**Comment by asar0786** [comment]
Hi @agrohsje 
I have tried with the branch mg261. Here I also find the [patch](https://github.com/cms-sw/genproductions/blob/mg261/bin/MadGraph5_aMCatNLO/patches/0015-fix-critical-madspin-bug.patch) pointed by you in the patch directory. So, I just run the gridpack generation command. Since its there in the patch directory so it should automatically apply. Now, I get the gridpack without any error but the LHE file does not have any reweight points that I added in my reweight card. You can see the generated LHE file with mg261 here[1].

The same thing happended with the master branch. 

However, as mentioned earlier in branch mg265, I am getting the reweight values used in reweight card.

I am worried about the method used for gridpack production! Is there any special way to use patch file or I used it correctly? 

You can also see the generated LHE file from mg260 and mg265 in[1], just the prefix is distinguishing the version.

[1] LHE fifle location: /afs/cern.ch/user/a/asahmed/public/Test_LHE_Files

**Comment by agrohsje** [comment]
Hi @asar0786 , do you mind posting your gridpack generation log. That would be best for debugging. The patch will be applied in gridpack_generation.sh by doing 
cat patches/* | patch -p1

**Comment by asar0786** [comment]
Hi @agrohsje , You can find the logfiles[1] for  the grid pack generation
[1] /afs/cern.ch/user/a/asahmed/public/Test_LHE_Files/LogFiles/

Also I have applied the patch with above command and now producing gridpack. I will update you soon.

**Comment by agrohsje** [comment]
@asar0786 In an reply to Qiang you were saying that the problem in older versions was 
INFO: No independent decay for one type of final states -> skip those events for the maximum weight computation
which comes from Madspin. However, in the logs I don't see Madspin appearing.
Can you please post the exact cards you used to run the test for e.g. 2.6.1 ?

**Comment by asar0786** [comment]
Hi @agrohsje, Initially I was producing gridpack with Madspin, but found above warnings during decay. Now I have produced gridpack withmg265 for central production, this branch is not validated till now. As per @qliphy suggestion I was producing gridpacks with mg260, mg261, and mg265 to see some distribution to validate mg265. Since I was getting problem while decay in mg261, so I tried to see the distribution in all the branches without decay. 
I have deleted the gridpacks with decay, but now after applying the patch, I have started producing gridpack with madspin. I will update soon.

You can find all the card at[1], now I have added Madspin card as well.

[1] /afs/cern.ch/user/a/asahmed/public/Test_LHE_Files/cards/

**Comment by asar0786** [comment]
Hi @agrohsje  ,

I have produced gridpack using suggested patch[1] on mg261. To apply the patch I have used following command.
```bash
cat patches/* | patch -p1
```
Now, error does not appear. However, I did not get the lhe weight that I have put in reweight card. This time I have included madspin card for decay. You can find the gridpack, log file and lhe file on[2].
I am unable to understand the exact problem that I am facing.

[1] https://github.com/cms-sw/genproductions/blob/mg261/bin/MadGraph5_aMCatNLO/patches/0015-fix-critical-madspin-bug.patch
[2] `/afs/cern.ch/user/a/asahmed/public/mg261_patch0015_AllFiles/`

**Comment by agrohsje** [comment]
Hi @asar0786 ,
there is another PR missing for 261 and UL2019 as far as I can see which should update  
https://github.com/cms-sw/genproductions/blob/mg261/bin/MadGraph5_aMCatNLO/Utilities/gridpack_helpers.sh

Can you comment which genproduction branch you are using? Doing 
git clone -b mg261   https://github.com/cms-sw/genproductions.git 261
you should see an error like 
./gridpack_generation.sh: line 532: prepare_reweight: command not found
but I don't see that in your log file. 
I will test 2.6.1 with that fix. Will get back once I made the PR and tested.

**Comment by asar0786** [comment]
Hi @agrohsje ,
I was cloning from the command on twiki[1]

```git clone git@github.com:cms-sw/genproductions.git genproductions```

and then swithcing to the desired branch, for this case mg261.


[1] https://twiki.cern.ch/twiki/bin/viewauth/CMS/QuickGuideMadGraph5aMCatNLO

**Comment by agrohsje** [comment]
@asar0786 all the files are now there for 261. I didn't test 2.6.0 yet. In 261 I didn't see any problem. Please try and let me know. If you still have problems, send me your cards and I will test. As said it worked fine  including madspin.

**Comment by asar0786** [comment]
@agrohsje , are you able to see the weight used in reweight card, although we don't see any problem in producing lhe file, but I never get the reweight parameter in final lhe file produced from mg2.6.0 and mg2.6.1. However, from mg2.6.5 we can see the reweight parameters in final lhe file. you can find the card in[1].

[1] ```/afs/cern.ch/user/a/asahmed/public/Test_LHE_Files/cards/```

**Comment by asar0786** [comment]
Hi,
I have made small analysis on various Madgraph versions, i.e mg260,mg261 and mg265.
The distribution looks similer. The presentation can be found at[1].
Need validation of mg265 branch, so that submitted gridpacks to central production can be proccessed. 

[1] https://docs.google.com/presentation/d/1lNGzDNpe7_kttfN2-_kBvARrPiN1GL62vND8tCbEFEw/edit?usp=sharing

**Comment by qliphy** [comment]
@asar0786  Thanks!  The validation results look good.  You can go ahead with central production with mg265 gridpacks.  However, we would like you to give a report at coming GEN meetings. Are you available for July 23rd?  https://indico.cern.ch/event/783797/

**Comment by asar0786** [comment]
Thanks @qliphy ,
Yes, I will be available for July 23rd meeting to present the report.

**Comment by qliphy** [comment]
Good, you are now on the agenda: https://indico.cern.ch/event/783797/

**Comment by menglu21** [comment]
> @asar0786 Thanks! The validation results look good. You can go ahead with central production with mg265 gridpacks. However, we would like you to give a report at coming GEN meetings. Are you available for July 23rd? https://indico.cern.ch/event/783797/

is that mean the requests with mg265 gridpacks can be presented now?

**Comment by qliphy** [comment]
@menglu21  Unfortunately not yet.  MG265 currently is only for special requests as here (other MG version doesn't work) and after some further validation

**Comment by qliphy** [comment]
But we expect MG265 should be ready soon in ~ weeks.  We will make the announcement to hn

**Comment by menglu21** [comment]
> @menglu21 Unfortunately not yet. MG265 currently is only for special requests as here (other MG version doesn't work) and after some further validation

for these requests correspond to this pull, we need to reproduce the gridpacks with mg261?

**Comment by qliphy** [comment]
For aQGC VVjj, we gave greenlight to proceed with mg265.

**Comment by menglu21** [comment]
> For aQGC VVjj, we gave greenlight to proceed with mg265.

ok, i'll present them.

**Comment by agrohsje** [comment]
@asar0786 the reason that you don't see the weights in your lhe file in 2.6.1 is that you are using "change output 2.0" in your reweight card. this causes the lhe files to be regenerated for each event and the weight is not just added to the existing lhe. can you send me your 2.6.5 gridpack. it is not clear to me why including this option in 2.6.5 is not causing this problem. as said, if I remove this option everything is working well for me in 2.6.1.

**Comment by asar0786** [comment]
@agrohsje, 
Initially, I tried to produce gridpacks without "change output 2.0" in 2.6.1, but there were warnings to include it in the reweight card. However its good to hear that you are able to produce lhe file with reweight parameters.
You can find the gridpacks produced using mg265 at[1]

[1] ```/eos/uscms/store/user/asahmed/Gridpacks_VVJJ```

**Comment by agrohsje** [comment]
@asar0786 Thanks. That explains the differences between 2.6.1 and 2.6.5. The change output 2.0 will produce separate files and our scripts don't expect this and they cannot handle it. Just to conclude this thread, there is no problem with 2.6.1 and a correct reweight card will produce correct results.

**Comment by asar0786** [comment]
@agrohsje,
If you see the final LHE file precisely produced, either using "change output 2.0" or not in the reweight card, you will not find any of the reweight values used in the reweight card.
For example in the LHE file produced from mg261 using **"change output 2.0"** or skipping **"change output 2.0"**, you will see the default weight values like

```
<rwgt>
<wgt id='1001'> +1.3863362e-02 </wgt>
<wgt id='1002'> +1.0150678e-02 </wgt>
.
.
.
<wgt id='1918'> +2.9189333e-02 </wgt>
<wgt id='1919'> +2.0178800e-02 </wgt>
</rwgt>
```

But if you produce the gridpack using mg265, we can see the reweight values in the lhe file that were used in reweight card, along with default values, For example
```
<rwgt>
<wgt id='1'> +9.1495585e-03 </wgt>
<wgt id='2'> +1.0581754e-02 </wgt>
.
.
.
<wgt id='145'> +9.6408042e-03 </wgt>
<wgt id='146'> +1.0286819e-02 </wgt>
<wgt id='ft1_0'> +8.8356435e-07 </wgt>
<wgt id='ft1_m0p02'> +1.1568689e-06 </wgt>
<wgt id='ft1_0p02'> +6.5433454e-07 > </wgt>

.
.
.
<wgt id='ft9_m10'> +8.8356435e-07 </wgt>
<wgt id='ft9_10'> +8.8356435e-07 </wgt>
<wgt id='1001'> +9.1495585e-03 </wgt>
<wgt id='1002'> +6.7868843e-03 </wgt>.
.
.
.
<wgt id='1918'> +1.3118803e-02 </wgt>
<wgt id='1919'> +1.2847434e-02 </wgt>
</rwgt>
```

Here we concerned with the inclusion of reweight values in the LHE file i.e used in the reweight card. They appear above in weights as

```
<wgt id='ft1_m0p02'> +1.1568689e-06 </wgt>
<wgt id='ft1_0p02'> +6.5433454e-07 > </wgt>

.
.
.
<wgt id='ft9_m10'> +8.8356435e-07 </wgt>
<wgt id='ft9_10'> +8.8356435e-07 </wgt>
```

But, I can't see these in mg260 or mg261.

For my clarification, I would like to see the gridpack and final LHE file that you are producing using mg261.

**Comment by agrohsje** [comment]
I copied an untarred gridpack and the cmsgrid_final.lhe to http://www.desy.de/~agrohsje/hidden/asar/debug/ .
Event weights per event included.

**Comment by asar0786** [comment]
@agrohsje , 
The file you shared is not readable in the lhe format, maybe due HTML syntax.
Please share  this file via lxplus public space.
Thanks

**Comment by agrohsje** [comment]
wget http://www.desy.de/~agrohsje/hidden/asar/debug/cmsgrid_final.lhe
will do the job.

**Comment by asar0786** [comment]
Thanks @agrohsje , 
Yes I can see the reweight. Probably I haven't applied the patch in the right way. 
I need to produce the gridpack from scratch. Can we meet for a while if you at CERN? It will definitely help me a lot to solve the problem I am facing

**Comment by asar0786** [comment]
@agrohsje , one more thing I forgot to mention, I acn't see the following pdf weights
```<rwgt>
<wgt id='1'> +9.1495585e-03 </wgt>
<wgt id='2'> +1.0581754e-02 </wgt>
.
.
.
<wgt id='145'> +9.6408042e-03 </wgt>
<wgt id='146'> +1.0286819e-02 </wgt>```
 Are these same weights which are from id= 1001 to id= 1919 or different one?
Thanks

**Comment by agrohsje** [comment]
you need to check the exact meaning of these ideas in the header. in cms we usually start counting at 1001, while mg5_amc@nlo starts with 1. the meaning is always clarified in the header.

**Comment by agrohsje** [comment]
@asar0786 I am currently at Fermilab and will be offline for 2 weeks starting Monday. Everything should work if you start from a clean 261 branch genproduction. There is nothing one should apply by hand. My input cards just removed the change output 2.0 as discussed.
Note that there is one PR missing to correct buggy systematics weights, however, this is unrelated to what we are discussing here.

**Comment by ram1123** [comment]
@asar0786 & @agrohsje ,

As @asar0786  is not able to reproduce what @agrohsje saw I tried to run the same.

```bash
git clone git@github.com:cms-sw/genproductions.git
cd genproductions/
git checkout mg265
git checkout mg261
# Just to get the aQGC cards from mg265 branch I run below command
git checkout mg265 -- bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/VBS/VVjj_semileptonic
./gridpack_generation.sh aQGC_ZlepZhadJJ_EWK_LO_NPle1_mjj100pt10 cards/production/2017/13TeV/VBS/VVjj_semileptonic/aQGC/aQGC_ZlepZhadJJ_EWK_LO_NPle1_mjj100pt10
```

Then while producing the gridpack it gives below error message. However it produce the gridpack.

```error
INFO: Extracting the banner ... 
INFO: process: p p > z z j j QED=4 QCD=0  
INFO: options: NP=1 
INFO: Running Reweighting 
change rwgt_dir rwgt
launch --rwgt_name=FT1_0
INFO: detected model: SM_LS_LM_LT_UFO. Loading... 
INFO: generating the square matrix element for reweighting 
INFO: generate p p > z z j j QED=4 QCD=0 NP=1 ; 
INFO: Done 100.2 
Command "reweight /uscmst1b_scratch/lpc1/3DayLifetime/rasharma/genproductions/bin/MadGraph5_aMCatNLO/aQGC_ZlepZhadJJ_EWK_LO_NPle1_mjj100pt10/aQGC_ZlepZhadJJ_EWK_LO_NPle1_mjj100pt10_gridpack/work/process/madevent/Events/pilotrun/unweighted_events.lhe.gz_0.lhe -from_cards --multicore=create" interrupted with error:
AttributeError : 'Model' object has no attribute 'get_mass'
Please report this bug on https://bugs.launchpad.net/mg5amcnlo
More information is found in '/uscmst1b_scratch/lpc1/3DayLifetime/rasharma/genproductions/bin/MadGraph5_aMCatNLO/aQGC_ZlepZhadJJ_EWK_LO_NPle1_mjj100pt10/aQGC_ZlepZhadJJ_EWK_LO_NPle1_mjj100pt10_gridpack/work/process/madevent/Events/pilotrun/unweighted_events.lhe.gz_0.lhe_tag_1_debug.log'.
Please attach this file to your report.
quit
INFO: storing files of previous run 
INFO: Done 
INFO:
```

When I tried to generate the LHE file from generated gridpack then it produced the LHE file with almost same error but it does not have the reweight information. It should not as while generating the gridpack it has issue while processing the reweight information.

@agrohsje : I think sometime might be missing from github that you have there in your local repository. So, please check this.

with regards,
Ram

**Comment by agrohsje** [comment]
Dear @asar0786 @ram1123 ,
unfortunately it seems more complicated than that. Nothing missing from my  side. I just tested ZW and it works fine and ZZ doesn't. The only difference between the two setups is the process line, reweighting cards are the same. I updated the reweight interface a little more and everything is working in 2.6.1. I will make a PR asap (might take a little time as I am travelling to CERN and will be busy with meetings) but that should help us getting rid of these spurious errors. 
Now about what you did in 2.6.5. I checked your gridpack :   aQGC_ZlepZhadJJ_EWK_LO_NPle1_mjj100pt10_slc6_amd64_gcc630_CMSSW_9_3_8_tarball.tar.xz
and there are errors like 
command not executed: e
command not executed: d
command not executed: _
command not executed: e
command not executed: v
command not executed: e
command not executed: n
command not executed: t
command not executed: s
This is a syntax problem. I updated 2.6.5. already a while ago but it seems like you used the framework before that fix. I will try to make a 2.6.5 gridpack and check. 
Cheers, Alexander.

**Comment by ram1123** [comment]
> Dear @asar0786 @ram1123 ,
> unfortunately it seems more complicated than that. Nothing missing from my side. I just tested ZW and it works fine and ZZ doesn't. The only difference between the two setups is the process line, reweighting cards are the same. I updated the reweight interface a little more and everything is working in 2.6.1. I will make a PR asap (might take a little time as I am travelling to CERN and will be busy with meetings) but that should help us getting rid of these spurious errors.
> Now about what you did in 2.6.5. I checked your gridpack : aQGC_ZlepZhadJJ_EWK_LO_NPle1_mjj100pt10_slc6_amd64_gcc630_CMSSW_9_3_8_tarball.tar.xz
> and there are errors like
> command not executed: e
> command not executed: d
> command not executed: _
> command not executed: e
> command not executed: v
> command not executed: e
> command not executed: n
> command not executed: t
> command not executed: s
> This is a syntax problem. I updated 2.6.5. already a while ago but it seems like you used the framework before that fix. I will try to make a 2.6.5 gridpack and check.
> Cheers, Alexander.

Hi @agrohsje ,

As I stated in my previous reply. The steps that I followed is 

```
git clone git@github.com:cms-sw/genproductions.git
cd genproductions/
git checkout mg265
git checkout mg261
# Just to get the aQGC cards from mg265 branch I run below command
git checkout mg265 -- bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/VBS/VVjj_semileptonic
./gridpack_generation.sh aQGC_ZlepZhadJJ_EWK_LO_NPle1_mjj100pt10 cards/production/2017/13TeV/VBS/VVjj_semileptonic/aQGC/aQGC_ZlepZhadJJ_EWK_LO_NPle1_mjj100pt10
```

So, If you did not commit any thing after 24th July then it points to only two possibility.

1. Either there is some environment setup issue becuase of which this is happening.
2. Some updates are missing in the latest commit which is available locally to you but not us.

Please let us know what you think might be the issue.

**Comment by agrohsje** [comment]
The official ZZ gridpack has the following line: 
Starting job on  Thu Jun 27 04:16:18 CDT 2019
Running on  Linux cmslpc34.fnal.gov 2.6.32-754.12.1.el6.x86_64 #1 SMP Tue Apr 9 08:24:46 CDT 2019 x86_64 x86_64 x86_64 GNU/Linux
System release  Scientific Linux Fermi release 6.10 (Ramsey)
name: aQGC_ZlepZhadJJ_EWK_LO_NPle1_mjj100pt10
so that misses the updates.

**Comment by ram1123** [comment]
@agrohsje ,

Sorry, I did not understand, what you want to day.

**Comment by agrohsje** [comment]
@ram1123 My comment was about the official 2.6.5 gridpack: 
https://cms-pdmv.cern.ch/mcm/requests?prepid=SMP-RunIIFall18wmLHEGS-00152&page=0&shown=524415
Like said the other difference need to be cured with a patch for the reweight_interface. It didn't appear for me because I was running WZ for validation while you used ZZ.
