### ISSUE TITLE
[mg] MG compiling error with lhapdf v621

### ISSUE THREAD

**Issue by perrozzi** [cms-sw/genproductions#1345]
HN: https://hypernews.cern.ch/HyperNews/CMS/get/generators/3595.html
Launchpad: https://bugs.launchpad.net/mg5amcnlo/+bug/1719165

**Comment by qliphy** [comment]
We got reply from Olivier.  He mentioned some patch for lhapdf621 [1],  from which I have prepared a file for MG242 :
[0014-lhapdf62x.patch.txt](https://github.com/cms-sw/genproductions/files/1327364/0014-lhapdf62x.patch.txt)

Note in the patch I don't include the modification in madgraph/interface/common_run_interface.py 
And moreover, I have moved here relevant part from previous 0013-fix-cluster-local-path.patch

A quick check, however, shows this patch doesn't work.  As Olivier mentioned in his reply, "Now I do now(t) know if such patch will fix your problem (I have some doubt). The error message seems to indicate a problem with your boost library."

@kdlong @bendavid   Would you please have a look at this?

[1]http://bazaar.launchpad.net/~mg5core1/mg5amcnlo/2.5.6/revision/324

**Comment by perrozzi** [comment]
Thanks for the feedback. Indeed there was a change concerning boost in 7_1_30
https://github.com/cms-sw/cmsdist/pull/3438
but related to Pythia. It looks strange to me that this has consequences for mg5_amc, the only possibility that comes to my mind is that it creates a clash in the internal mg5_amc to pythia link (if any).
Puzzling...

**Comment by kdlong** [comment]
I posted a response with more information on the LHAPDF issue on the launchpad. 

After adding the missing includes, the error is coming from inside LHAPDF. The function LHAPDF::lookupPDF(lhaid) fails with an error that the pdfsets.index file can’t be found. Can someone else who is an expert in this do a trivial check that the installation is actually configured properly? I think it would be sufficient to write a dummy script that accesses these functions and is properly compiled against the LHAPDF installation in CMSSW_7_1_30 or CMSSW_9_3_0.

**Comment by perrozzi** [comment]
@alberto-sanchez @mkirsano please help. This is very urgent
@kdlong please provide further info about your latest checks

**Comment by alberto-sanchez** [comment]
@perrozzi looking into this, but not clear idea what is going on. From the discussion at the launchpad forum it seems that 6.2.x is not fully tested. So, to me, the quick solution would be downgrade to 6.1.6(a), but we will be restricted just to the PDFs available.

**Comment by alberto-sanchez** [comment]
@perrozzi , all :  I manage to do a quick test, and seems that 6.1.6a is easily to go. In 
/afs/cern.ch/work/a/asanchez/public/genproductions/bin/MadGraph5_aMCatNLO/gridpack_generation.sh I put a modified script which uses the file force_616a.patch in the same directory for 
downgrade in fly the LHAPDF to 6.1.6a. With that, the command 

./gridpack_generation_ori.sh wplustest_4f_LO cards/examples/wplustest_4f_LO 1nd 

run without any problem. Hope this speed up the fix!.

**Comment by qliphy** [comment]
@alberto-sanchez

Thanks!  But although the gridpack can be generated,  running it to produce events doesn't work due to lack of several PDF sets (on 4 flavor), which currently only exit in LHAPDF621.

Those PDF sets are for LO as set in runcmsgrid.sh:
  NNPDF31_nnlo_as_0118_nf_4.LHgrid
  NNPDF31_nlo_as_0118_nf_4.LHgrid
  NNPDF30_nlo_as_0118_nf_4.LHgrid
  NNPDF30_lo_as_0118_nf_4.LHgrid 1
  NNPDF30_lo_as_0130_nf_4.LHgrid 1
  NNPDF30_nlo_nf_4_pdfas.LHgrid
  NNPDF30_nnlo_nf_4_pdfas.LHgrid 1
or in run_card.dat for NLO
   322500,322700,322900,323100,323300,323500,323700,323900

https://hypernews.cern.ch/HyperNews/CMS/get/generators/3573/1/1/1/1.html

**Comment by efeyazgan** [comment]
@alberto-sanchez  and @mkirsano could you please contact lhapdf people a.s.a.p?

**Comment by bendavid** [comment]
This is affecting LO, or NLO, or both?

**Comment by kdlong** [comment]
Both. I think the LHAPDF interface is the same.

**Comment by bendavid** [comment]
Testing standalone with mg_amc 2.6.0 in LO mode everything works correctly with both LHAPDF 6.1.6 and 6.2.1.

Using 6.2.1 I get a warning "WARNING: Support of LHAPDF 6.2.x is still in beta phase. Consider to use LHAPDF 6.1.x in case of problem. " but this doesn't interfere with compiling or producing events.

**Comment by perrozzi** [comment]
btw, standalone mg_amc using standalone lhapdf, right? (because kenneth had tested standalone mg_amc with cmssw lhapdf)

**Comment by bendavid** [comment]
So I should say that the environment in which I test this is quite different from anything used in cms.  (Arch linux with bleeding edge everything, plus a python venv to get python 2.7 instead of 3.x)

Yes it's standalone mg_amc and standalone lhapdf (any anything else needed pulled in from my system installation)

**Comment by bendavid** [comment]
If I try to add the boost includes manually in the cms environment case I get
"pdf_lhapdf6.cc:15:32: fatal error: boost/shared_ptr.hpp: No such file or directory"

**Comment by agrohsje** [comment]
/LHAPDF-6.1.6/src/LHAGlue.cc is using boost while 6.2.1 was rewritten. The same functions are implemented in the MG5 interface:  
./Template/NLO/Source/PDF/pdf_lhapdf6.cc  
./Template/LO/Source/PDF/pdf_lhapdf6.cc
They still rely on boost.

**Comment by bendavid** [comment]
I managed to completely remove boost dependencies from this file, but still get the runtime error Kenneth reported.  So it seems to me there are two separate issues  here.

**Comment by bendavid** [comment]
I have a (hacky) set of patches that fixes this in the 2.6.x branch.

Should be straightforward to adapt to 2.4.x together with the patch Olivier already provided.

There are two separate problems.
1) Boost is not found.
Can be solved either by 
a) fixing includes as Kenneth proposed (but this did not work for me)
b) removing boost dependencies from madgraph lhapdf interface and then forcing use of c++11 (since this is needed to substitute the boost functionality which is used).  This means that CMSSW 53x support is gone, but not needed anymore with environment portability

2) Functionality to determine and set LHAPDF data path in fortran is broken, but it's sufficient to just comment this out, because LHAPDF can figure this out for itself based on the $LHAPDF_DATA_PATH environment variable, which gets correctly set in CMSSW

Will attach needed patches in a moment

**Comment by bendavid** [comment]
Patches for 2.6.x branch here, @kdlong can you adapt these to 24x together with the other patch from Olivier?

[mg26xlhapdf62xpatch.txt](https://github.com/cms-sw/genproductions/files/1334073/mg26xlhapdf62xpatch.txt)

**Comment by perrozzi** [comment]
Awesome, thanks!

**Comment by alberto-sanchez** [comment]
looks like we do not need to force c++11, adding the few missing headers for boost and comment out the LHAPDF data path in fortran is enough to make it work with lhapdf 6.2.1. Found this by accident since I missed the patch provided by Oliver.

we just need to put the attach patch in the "patches" directory and should be work out of the box for 24x.

[0015-boost-setpdf.patch.txt](https://github.com/cms-sw/genproductions/files/1334405/0015-boost-setpdf.patch.txt)

**Comment by perrozzi** [comment]
@alberto-sanchez great, thanks! May I kindly ask you to create a PR if possible?

**Comment by alberto-sanchez** [comment]
@perrozzi done!

**Comment by perrozzi** [comment]
thanks! (https://github.com/cms-sw/genproductions/pull/1362)

**Comment by bendavid** [comment]
Ok even better, but in 2.6.x adding the boost includes did not work for some reason.

If we go this way can we please triple check that boost is being correctly taken from what is included with cmssw and not from the system libraries (otherwise we risk undefined behaviour in production)

**Comment by alberto-sanchez** [comment]
I have checked the logfiles, and at least there, the cms boost includes are used.

 I have repeat the tests with 9_3_1, and for both examples run OK.  

And lastly, I have switched to MG5_aMC v2.6.0, this time I applied just the patch for the boost header and the comment on LHAPDF data path in fortran (e.g. the patch above, 0015-boost-setpdf.patch.txt) since I not sure if the other patches are needed and again both examples run for 7_1_30 and 9_3_1.

But, before going in production, more tests are needed, specially from the people producing gridpacks, which are more familiar than me.

**Comment by bendavid** [comment]
Indeed if adding the boost includes works then the only other thing needed is commenting the one line setting the lhapdf data path.  I don't understand why the boost includes were not working in my tests in that case though.  Did you try with both LO and NLO?

**Comment by alberto-sanchez** [comment]
Yes, I did wplustest_4f_LO and wplustest_4f_NLO.

**Comment by kdlong** [comment]
Great! @bendavid, what system are you running from, lxplus? Are you able to consistently reproduce the error, i.e. if you run with the patched genproductions scripts?

If so, maybe it's safer to remove the boost dependency.

**Comment by bendavid** [comment]
Hi, the patch from @alberto-sanchez does NOT work for me in the master branch with mg5_amc 2.4.x.

I am testing on a centos6 docker instance with cms environment sourced from cvmfs (where I successfully run cmssw and existing version of genproduction scripts.)

The errors  I get are as " pdf_lhapdf6.cc:15:32: fatal error: boost/shared_ptr.hpp: No such file or directory
             #include <boost/shared_ptr.hpp>"

What makes me very suspicious, this error occurs when I do NOT have boost and boost-devel packages installed on my centos6 docker instance.  If I install those two packages from the system repository, then it works.  This makes me almost 100% sure that the boost headers are being picked up from the system installation instead of from CMSSW, which means we either need to muck around further with the config and/or build files to ensure this is not the case, or else just remove the boost dependency.

@alberto-sanchez can you point me to which output in the logs suggests that boost was being taken from CMSSW?  Boost is also used for compiling SysCalc (also removed in the 26x branch) but here I made sure that the scripts properly take it from CMSSW, so maybe this is what you saw in the logs.

**Comment by kdlong** [comment]
@bendavid if you already have a patch that replaces boost functions with C++11 std library ones then I vote we just use that. It seems more straightforward than enforcing the proper boost include.

**Comment by bendavid** [comment]
Yes, agreed.

We'd also better check with the authors about possible differences between my patch and what they've implemented here
https://code.launchpad.net/~maddevelopers/mg5amcnlo/2.6.1_lhapdf62

**Comment by kdlong** [comment]
This is a pretty extensive change, and I assume it won't be merged into the release branch for some time. I would be hesitant to have a 1600 line patch file unless it's really needed, so if you're confident in the robustness of your changes I'd vote to just merge those ASAP.

**Comment by bendavid** [comment]
Yes, I'm not suggesting to add that patch, I'm suggesting to ask the authors what issues that patch is supposed to address, in order to make sure we aren't missing anything with the more minimal change.

**Comment by alberto-sanchez** [comment]
My working area in lxplus is: /afs/cern.ch/work/a/asanchez/public/genproductions-plain/bin/MadGraph5_aMCatNLO 

I have repeat your test in a VM without boost, and it fail founding the boost headers

**Comment by alberto-sanchez** [comment]
I think I have found the way for forcing the use of cms boost. I will add that to the PR

**Comment by perrozzi** [comment]
#1362 merged, issue should be solved
